### ISSUE TITLE
trying to install, get error: Cannot find module '/opt/TidalWave/build/server/server.js'

### ISSUE THREAD

**Issue by zeigerpuppy** [MisterTea/TidalWave#8]
I have attempted to install using the following procedure on Debian Jessie:

```
cd /opt
git clone https://github.com/MisterTea/TidalWave.git
cd /TidalWave
npm install
```

I get a few warnings after installing but nothing major:

```
npm WARN package.json angular-bootstrap@0.12.2 No README data
npm WARN package.json highlightjs@8.7.0 No repository field.
npm WARN cannot run in wd TidalWave@0.0.0 npm run bower ; npm run buildClient ; npm run tsd ; npm run buildServer (wd=/opt/TidalWave)
```

When I try to `npm start`, it throws the error:

```
> TidalWave@0.0.0 start /opt/TidalWave
> node build/server/server.js --optionsFile=options.json | ./node_modules/.bin/bunyan


module.js:340
    throw err;
          ^
Error: Cannot find module '/opt/TidalWave/build/server/server.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

any ideas, the file doesn't seem to exist?

**Comment by MisterTea** [comment]
It sounds like the typescript compiler didn't compile the js files.  Can
you verify by manually npm starting the typescript compile task and seeing
if the problem goes away?

**Comment by zeigerpuppy** [comment]
ok, I went from scratch and found an error in building microtime,
but it does say this is optional

```
make: Entering directory `/opt/TidalWave/node_modules/selectize/node_modules/sifter/node_modules/microtime/build'
  CXX(target) Release/obj.target/microtime/src/microtime.o
In file included from ../src/microtime.cc:9:0:
../node_modules/nan/nan.h:316:47: error: 'REPLACE_INVALID_UTF8' is not a member of 'v8::String'
   static const unsigned kReplaceInvalidUtf8 = v8::String::REPLACE_INVALID_UTF8;
                                               ^
make: *** [Release/obj.target/microtime/src/microtime.o] Error 1
make: Leaving directory `/opt/TidalWave/node_modules/selectize/node_modules/sifter/node_modules/microtime/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 3.2.0-4-amd64
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /opt/TidalWave/node_modules/selectize/node_modules/sifter/node_modules/microtime
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm WARN optional dep failed, continuing microtime@2.0.0
```

then later in the install it fails with:

```
> TidalWave@0.0.0 buildServer /opt/TidalWave
> tsc --sourcemap --module commonjs --outDir build server/server.ts tools/*.ts

error TS6053: File 'tools/*.ts' not found.

npm ERR! TidalWave@0.0.0 buildServer: `tsc --sourcemap --module commonjs --outDir build server/server.ts tools/*.ts`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the TidalWave@0.0.0 buildServer script.
npm ERR! This is most likely a problem with the TidalWave package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc --sourcemap --module commonjs --outDir build server/server.ts tools/*.ts
npm ERR! You can get their info via:
npm ERR!     npm owner ls TidalWave
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.2.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "run" "buildServer"
npm ERR! cwd /opt/TidalWave
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /opt/TidalWave/npm-debug.log
npm ERR! not ok code 0

npm ERR! TidalWave@0.0.0 postinstall: `npm run bower ; npm run buildClient ; npm run tsd ; npm run buildServer`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the TidalWave@0.0.0 postinstall script.
npm ERR! This is most likely a problem with the TidalWave package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run bower ; npm run buildClient ; npm run tsd ; npm run buildServer
npm ERR! You can get their info via:
npm ERR!     npm owner ls TidalWave
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.2.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /opt/TidalWave
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /opt/TidalWave/npm-debug.log
npm ERR! not ok code 0
```

the tools folder has three files:

```
CreateIndex.js  LDAPExtractor.js  UpdateLDAP.js
```

perhaps the command above is failing because there are no .ts files left in that dir?
